### ISSUE TITLE
Upload downloaded file before downloading entire playlist and private video bug

### ISSUE THREAD

**Issue by testerbot11** [tgbot-collection/ytdlbot#115]
First off, thanks for this amazing bot. my issues: 1) when downloading a playlist contating for example 50 videos, currently bot downloads all 50 videos first, then starts uploading one by one. If possible, Instead if it is made to upload each video first before beginning next download of second video, space consumption in local drive is minimised and will bw hwlpful for those with limited drive space (like me)
2) If there is a private or deleted video in a playlist, all the downloads stop. instead if there is an ability to skip those videos and download and upload others, it will be more useful. Thanks.

**Comment by BennyThink** [comment]
Good advice - I'll see how to implement this.
