### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ananth-28** [tgbot-collection/ytdlbot#121]
![image](https://user-images.githubusercontent.com/106482929/174132150-52b7dada-6141-403b-a67a-971677dd2520.png)

**Comment by EDM115** [comment]
Hmmm there is a problem of versioning somewhere  
Check the dependancy graph, it may help

**Comment by BennyThink** [comment]
Will fix later this week.

**Comment by BennyThink** [comment]
should be fixed. try again.
