### ISSUE TITLE
Covert to Audio Button does Not work. 

### ISSUE THREAD

**Issue by oneandonlyjason** [tgbot-collection/ytdlbot#126]
Hi,

It seems like the "Convert to Audio Button" under a downloaded Video doesnt seem to work.

![Screenshot_2022-06-24-16-28-56-02_3d419158bad5872c40592a6c9956e692__01.jpg](https://user-images.githubusercontent.com/55148433/175557307-e44ea620-8811-4886-9d86-741ff35f3e59.jpg)

This is the Error Message that gets shown (sry i cant copy it right now so only Screenshot is possible)

**Comment by BennyThink** [comment]
could be a bug, can you share your video link?

**Comment by oneandonlyjason** [comment]
I tested it with different Videos

http://www.youtube.com/watch?v=JIZ2YRbrCwg
http://www.youtube.com/watch?v=ZQKdayVotaI
http://www.youtube.com/watch?v=UWDiVPnS1tg
http://www.youtube.com/watch?v=I9cKQ1lpr0w

This are some of them.
Selecting Audio in the Settings and Providing the Link works. Its just when i download the Video as MP4 and then use the Convert to Audio Button under the Message when it provides the MP4

**Comment by BennyThink** [comment]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/14024832/175774972-24275a3b-bc2e-4516-9f32-80b6a0a966df.png">

seems ok to me. Are you using the bot with latest code/image?

**Comment by oneandonlyjason** [comment]
Tested it on Both, Your Bot and my Bot and the Latest image that did not have the "Crash" Issue

**Comment by BennyThink** [comment]
> Tested it on Both, Your Bot and my Bot and the Latest image that did not have the "Crash" Issue

Are you talking about this? https://github.com/tgbot-collection/ytdlbot/issues/124

**Comment by oneandonlyjason** [comment]
Yeah i edited my Answer to make it more clear :D

**Comment by oneandonlyjason** [comment]
I tested it again on your Bot. Video Download finished in around 1 Minute Convert to Audio probably crashed again

![Screenshot_2022-06-25-15-22-16-46_948cd9899890cbd5c2798760b2b95377.jpg](https://user-images.githubusercontent.com/55148433/175775393-9489c369-7d4c-4bed-adbf-f5c461a76daa.jpg)

**Comment by BennyThink** [comment]
Guess it's bug. I'll debug tomorror

**Comment by BennyThink** [comment]
Can't reproduce. Can you try it again?

**Comment by oneandonlyjason** [comment]
Sadly it still happens. Your Bot doesnt answer and my bot doesnt answer either. And i can still see the Error in the Console of my Bot

![Screenshot_2022-06-26-09-03-44-76.jpg](https://user-images.githubusercontent.com/55148433/175803395-60678c13-f4de-4f07-b672-c4e66f1f05a7.jpg)

Is there something i can do to debug on my Bot Side?

**Comment by BennyThink** [comment]
I tried this link again, on the latest image: https://www.youtube.com/watch?v=JIZ2YRbrCwg

and no error.

**Comment by oneandonlyjason** [comment]
Checked Again and i dont really understand it

This Link now also Worked for me:
![image](https://user-images.githubusercontent.com/55148433/175809104-a943db08-a42a-4813-bd46-6bcdb6ed894a.png)

But another did not:
![image](https://user-images.githubusercontent.com/55148433/175809199-01691a12-e700-433b-9e19-e2f70a46e762.png)

**Comment by oneandonlyjason** [comment]
Ohhhhh I think i Figured it out!!

When i search for a Youtube Video over Telegrams Inline Bot @vid the Link starts with http://.... This is the Moment the Button failed. When i then use the Same Link and add an s so that i get https:// the Button Works!!

**Comment by BennyThink** [comment]
Good catch. http -> https.

**Comment by oneandonlyjason** [comment]
Maybe [this](https://pythex.org/?regex=(%3F%3Ahttps%3F%3A%5C%2F%5C%2F)%3F(%3F%3Awww%5C.)%3Fyoutu%5C.%3Fbe(%3F%3A%5C.com)%3F%5C%2F%3F.*(%3F%3Awatch%7Cembed)%3F(%3F%3A.*v%3D%7Cv%5C%2F%7C%5C%2F)(%5B%5Cw%5C-_%5D%2B)%5C%26%3F&test_string=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DiP6XpLQM2Cs%0Ahttps%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DiP6XpLQM2Cs%0Ahttp%3A%2F%2Fyoutu.be%2FI9cKQ1lpr0w%0Ahttps%3A%2F%2Fyoutu.be%2FI9cKQ1lpr0w&ignorecase=0&multiline=0&dotall=0&verbose=0) helps?

**Comment by BennyThink** [comment]
fixed. Image was pushed.
