### ISSUE TITLE
Add all thumbnail upload support

### ISSUE THREAD

**Issue by vuisme** [tgbot-collection/ytdlbot#157]
I'm using old TG Bot (https://github.com/Tellybots/Uploader-Bot-V2) and can send all Image thumbnail after download with **--write-all-thumbnails** option agrument. Can you support it?

**Comment by BennyThink** [comment]
What's the purpose of adding all thumbnails? Are you saying I should download thumbnail from YouTube instead of generating my own?

**Comment by dlcvietnam** [comment]
> What's the purpose of adding all thumbnails? Are you saying I should download thumbnail from YouTube instead of generating my own?

Not only youtube. In some case we get all thumbnail from movie poster, album artwork, amazone image... This is my code for upload this
`
                lstimg = []
                for r, d, f in os.walk(tmp_directory_for_each_user):
                    for file in f:
                        path = os.path.join(r, file)
                        size = os.stat(path).st_size # in bytes
                        if ('.jpg' in file or '.png' in file) and size > 5000:
                            lstimg.append(
                                InputMediaPhoto(
                                    media=os.path.join(r, file)
                                )
                            )
                newlst=split_list(lstimg, 10)
                for array in newlst:
                    await bot.send_media_group(
                        chat_id=update.message.chat.id,
                        disable_notification=True,
                        reply_to_message_id=update.message.message_id,
                        media=list(array)
                        )
`

**Comment by dlcvietnam** [comment]
#160
