### ISSUE TITLE
Add permanent thumbnail 

### ISSUE THREAD

**Issue by DeMoL2021** [tgbot-collection/ytdlbot#17]
Please add permanent thumbnail please

**Comment by BennyThink** [comment]
Will do later

**Comment by BennyThink** [comment]
# before
![image](https://user-images.githubusercontent.com/14024832/144748653-b86aa071-30fc-4477-840f-b9f7b2421369.png)

# after
![image](https://user-images.githubusercontent.com/14024832/144748658-15b64009-b752-4101-a0b5-18b10a34b341.png)
