### ISSUE TITLE
parsing youtube-dl flags/parameters/commands

### ISSUE THREAD

**Issue by A5DkjGQUZx** [tgbot-collection/ytdlbot#177]
Hi
I have a suggestion whcih might be useful! The ability to send flags/commands to youtube-dl to get responses or to get a specific file.
for example send `-f 1640 --hls-prefer-native -c -o "file.mp4"` to get a specific resolution of HLS file or to send `-F` and get a reply back with list of availbale formats.

**Comment by BennyThink** [comment]
I would say this is won't fix because the code is not so compatible with this feature.
