### ISSUE TITLE
希望除了heroku之外还可以增加更多便捷搭建选项

### ISSUE THREAD

**Issue by Dover715** [tgbot-collection/ytdlbot#183]
感谢大佬提供的bot，非常好用。
不过现在heroku已经不再免费了，希望大佬可以帮助在其它免费的托管服务商那里设置一下一键搭建。谢谢
据我了解，Adaptable和cyclic目前应该可以提供可用的免费服务

**Comment by BennyThink** [comment]
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/14024832/210618183-041c3d70-1cf9-4fcc-a3fa-81ad60fec329.png">
<img width="706" alt="image" src="https://user-images.githubusercontent.com/14024832/210618219-3f6ff39f-50c0-4b35-a670-6dd97082080b.png">

**Comment by BennyThink** [comment]
测试了一下，adpative不太合适，它是web application，只有在接受到请求对时候才会使用CPU，其他时候都是被冻结CPU的。如果强行使用会导致下载上传很慢，另外一种办法 要把整个应用重写为webhook的模式，代价太大了。
