### ISSUE TITLE
Convert to mp3 issue

### ISSUE THREAD

**Issue by A5DkjGQUZx** [tgbot-collection/ytdlbot#186]
The downloader.py does not read `AUDIO_FORMAT` from config.py.
Added `AUDIO_FORMAT = "mp3"` on top of the downloader.py and it worked.

**Comment by BennyThink** [comment]
it shouldn't. Can you pull latest code and try again?

**Comment by BennyThink** [comment]
<img width="546" alt="image" src="https://user-images.githubusercontent.com/14024832/230715686-df499e79-e12c-4a22-90e1-3d30fc5fc58d.png">


works as expected. close as non issue
