### ISSUE TITLE
Issue with REQUIRED_MEMBERSHIP

### ISSUE THREAD

**Issue by Bartixxx32** [tgbot-collection/ytdlbot#198]
Issue is that i had tried setup "REQUIRED_MEMBERSHIP" and it worked, when tested on sub account but on main account its saying thats im not in the group "I`m owner of the group btw" 

I also tried doing myself as Authorized_user but also nothing changed

Some logs:
![image_2023-02-01_21-56-40](https://user-images.githubusercontent.com/16412925/216162732-7c590b31-1af5-4d5e-93d5-f37c9bc9fa41.png)
(dont look at comments marks (#) i did screenshot when disabled it)

![image_2023-02-01_21-57-09](https://user-images.githubusercontent.com/16412925/216162613-eedca1c4-35ce-4b23-8180-2be0cdd2d6df.png)
(Here log when tried as my main account (group owner))
![image_2023-02-01_22-00-07](https://user-images.githubusercontent.com/16412925/216162619-c7fd81b8-4736-4cb0-9fa8-45bc18fba405.png)
(here as sub account)
![image_2023-02-01_22-00-34](https://user-images.githubusercontent.com/16412925/216162873-69112eda-5935-43c6-a48e-57b1a6a55b17.png)

**Comment by vuisme** [comment]
```python
# membership check
        if REQUIRED_MEMBERSHIP:
            try:
                mship = app.get_chat_member(REQUIRED_MEMBERSHIP, chat_id).status
                if mship != "member" and mship != "creator" and mship != "administrator" and mship != "owner":
                    logging.info(mship)
                    raise UserNotParticipant()
                else:
                    logging.info(mship)
                    logging.info("user %s check passed for group/channel %s.", chat_id, REQUIRED_MEMBERSHIP)
            except UserNotParticipant:
                logging.warning("user %s is not a member of group/channel %s", chat_id, REQUIRED_MEMBERSHIP)
                message.reply_text(bot_text.membership_require, quote=True)
                return
        return func(client, message)
```
Shouldbe update check membership function

**Comment by BennyThink** [comment]
fixed in above commit. remember to add the bot to your group and set it as admin
