### ISSUE TITLE
Upload Files More Than 2Gb

### ISSUE THREAD

**Issue by itzrexmodz** [tgbot-collection/ytdlbot#204]
Recent introduction of telegram premium now allows user to upload files more than 4Gb. would it be possible to add like a session var which would make the user upload the file which exceeds 2Gb mark of the bot and the bot will just forward it to the user who has submitted the download link to the bot

**Comment by BennyThink** [comment]
Theoretically, yes. Premium user can upload file up to 4GiB. However,

1. I'm using an old version of pyrogram, it might not support upload bigger files
2. I don't like to rely on premium features.

**Comment by BennyThink** [comment]
Cool. I am actually think about to add 4GB support. Wait until Christmas so I can have some free time.

**Comment by rule-airport** [comment]
> Cool. I am actually think about to add 4GB support. Wait until Christmas so I can have some free time.

I can only make a rough thing based on the documentation, and I look forward to your perfect product.
