### ISSUE TITLE
heroku

### ISSUE THREAD

**Issue by TeaqariaWTF** [tgbot-collection/ytdlbot#207]
Help

![Screenshot_20230213-235857_Iceraven](https://user-images.githubusercontent.com/90970076/218573290-f91b3ed7-4703-464a-b3ce-1bf54486a422.png)

**Comment by BennyThink** [comment]
<img width="880" alt="image" src="https://user-images.githubusercontent.com/14024832/218574472-1891ba55-471c-4f3f-804f-b2e4e218719e.png">

**Comment by TeaqariaWTF** [comment]
![Screenshot_20230214-002903_Iceraven](https://user-images.githubusercontent.com/90970076/218578737-8a61493f-e227-4a90-be1e-d01ef7ec4be3.png)

![Screenshot_20230214-002913_Iceraven](https://user-images.githubusercontent.com/90970076/218578772-c2f38153-89bd-4b98-a520-1babad162739.png)

@BennyThink
