### ISSUE TITLE
 webm vp9 codec instead of AV1

### ISSUE THREAD

**Issue by Nijil321** [tgbot-collection/ytdlbot#216]
Sir, can you add Matroska / WebM Google VP9 codec on your YouTube downloader bot especially 4k videos. Because MPEG-4 dav1d AV1 decoder by VideoLAN codec doesn't support my phone. It's always lag. But webm vp9 codec videos work smoothly. I tried several video player including vlc player, but no use. I contacted you. You said open a issue here. Please help sir 🙏🙏🙏🙏
![Screenshot_20230308-045730_1](https://user-images.githubusercontent.com/127300108/223684481-e13d2384-8a90-491a-8339-5e2e8a2ff57f.jpg)
![Screenshot_20230308-045805_1](https://user-images.githubusercontent.com/127300108/223684561-09c3ea5f-956e-4ab6-bc31-9622e6797c3a.jpg)

**Comment by Nijil321** [comment]
https://youtu.be/KUN5Uf9mObQ

**Comment by Nijil321** [comment]
Thanks for the reply sir

**Comment by BennyThink** [comment]
turns out it's av1 is not supported on my phone and laptop as well. will fix

**Comment by BennyThink** [comment]
<img width="566" alt="image" src="https://user-images.githubusercontent.com/14024832/230719513-7a607dad-e672-4137-8493-3d812c27bc2f.png">


fixed. you can stream it now
