### ISSUE TITLE
Video Resolution Problem

### ISSUE THREAD

**Issue by AdityaDas5501** [tgbot-collection/ytdlbot#22]
I think the bot sends you the video in compressed form which lowers the video quality, can you provide an option so that the bot send the video uncompressed with the video's highest resolution. Telegram has that default compressing option which compresses the video to go fast but the thing I want is that there should be a option to choose where I want compressed or uncompressed video. Hopefully this will be added!

**Comment by Miteirao** [comment]
Yes, please add a resolution selection before downloading, like the parameter `-F`do in the command-line

**Comment by AdityaDas5501** [comment]
Yeah benny, please look into this issue, some people have limited data so they want low res video but some people have world's fastest internet and they want ultra 8k res video. Hope you understand 😀

**Comment by Miteirao** [comment]
I switched to a much better bot as it has `/lf` command and you can choose any video or audio tracking by using `/lf videoid+audioid url` like the PC command-line
https://t.me/YtbDownBot

**Comment by AdityaDas5501** [comment]
@Miteirao The bot is unavailable due to copyright infringement! Can't use it! 
![image](https://user-images.githubusercontent.com/95177019/145027006-198a9494-cc02-4c79-91cf-127ddc78bfdb.png)

**Comment by BennyThink** [comment]
![image](https://user-images.githubusercontent.com/14024832/145039576-75cdc068-9875-4b28-84f1-576122dc1167.png)

finished now.

**Comment by Miteirao** [comment]
> @Miteirao The bot is unavailable due to copyright infringement! Can't use it! ![image](https://user-images.githubusercontent.com/95177019/145027006-198a9494-cc02-4c79-91cf-127ddc78bfdb.png)

I switched to Termux + yt-dlp + ffmpeg
