### ISSUE TITLE
instagram videos are blurred on iOS devices

### ISSUE THREAD

**Issue by D1versy** [tgbot-collection/ytdlbot#239]
Do you know how I can fix the issue I'm having with my Instagram token where videos are blurred on iOS devices? I have to use it since Instagram locks my requests with a 429 Too Many Requests for unlogged in users.
![photo_2023-05-12_11-15-56](https://github.com/tgbot-collection/ytdlbot/assets/53017516/0bc295a7-76a4-412e-a4cb-cb66b354b5fc)

**Comment by D1versy** [comment]
The following video was uploaded by an anonymous user without logging in. (standard generated token)

https://github.com/tgbot-collection/ytdlbot/assets/53017516/0e84a064-7970-42fa-8351-e378cbe2a4db

**Comment by BennyThink** [comment]
![image](https://github.com/tgbot-collection/ytdlbot/assets/14024832/67f71c53-94c5-4c03-8e91-fab68b1162e6)


It's not blurred on my iPhone.... Can you try it again on my bot? https://t.me/benny_ytdlbot

**Comment by D1versy** [comment]
Did you use the .instagram.com session ID token instead of the standard one?

**Comment by BennyThink** [comment]
I actually use a third party service https://ssyoutube.com/

**Comment by D1versy** [comment]
It looks like it's fixed on your most recent commit, but I'm still using the previous one because it was much faster!
thank you for it solution https://ssyoutube.com/ you may close a ticket)

**Comment by BennyThink** [comment]
😭 seems like I'm doing bad optimization. Anyway thanks for reporting!
