### ISSUE TITLE
Instagram issue

### ISSUE THREAD

**Issue by Geraltboss** [tgbot-collection/ytdlbot#25]
Hi so when i send link to Instagram video, bot says : "You need to log in to access this content. Use --cookies, --username and --password, or --netrc to provide account credentials"

Is there a way to put the login and pass data to script ?

**Comment by BennyThink** [comment]
![image](https://user-images.githubusercontent.com/14024832/146666688-0f17f294-8e4b-4b52-a8b7-16cb649d849a.png)

fixed now
