### ISSUE TITLE
Ytdlbot don't work  

### ISSUE THREAD

**Issue by kang000feng** [tgbot-collection/ytdlbot#257]
Dear developer,

I  set up it with your docker compose yaml , and here's my screenshot of ytdl.env attached, 
 guide on this project doesn't refer the format of ytdl.env , not sure what is going wrong with my configuration, can you please give me some clues? Appreciate it very much.  
![E871CF49-A49E-4C48-A7A6-2500E508422A](https://github.com/tgbot-collection/ytdlbot/assets/9069317/ed1afd1c-e7ee-462c-9503-5f7ac4ff7c34)

**Comment by BennyThink** [comment]
```
cat env/ytdl.env

PYRO_WORKERS=100
TOKEN=170IluBY
APP_ID=123
APP_HASH=123

 
```

**Comment by kang000feng** [comment]
I set up ytdlbot for myself, and I only run 
 docker-compose up -d ytdl 

but my tg bot assigned doesn't work at all.

**Comment by BennyThink** [comment]
Please share some logs `docker-compose logs -f`

**Comment by kang000feng** [comment]
> # cat env/ytdl.env
> 
> PYRO_WORKERS=100
> TOKEN=170IluBY
> APP_ID=123
> APP_HASH=123


Thanks. Did you find out any problem with my ytdl.env?  Why your TOKEN is so short and my token is like " 123455:qwertyyyyhuyyu "

**Comment by kang000feng** [comment]
> Please share some logs `docker-compose logs -f`

![Uploading 28889D2B-DB08-4579-A4F8-3FD9ABC3B5D1.jpeg…]()

**Comment by BennyThink** [comment]
This is just an example config. This is the minimal configuration you'll need.

**Comment by kang000feng** [comment]
> This is just an example config. This is the minimal configuration you'll need.

![B6D2F6F0-5A01-44A1-BF01-2A34B153553A](https://github.com/tgbot-collection/ytdlbot/assets/9069317/a700ea8c-3929-4d98-bf42-ee854188a3d4)

**Comment by BennyThink** [comment]
Network issue. Maybe your ISP/country has blocked Telegram.

**Comment by kang000feng** [comment]
> Please share some logs `docker-compose logs -f`

Looks errors show address is unavailable , but my arm Oracle vps on Korean doesn't block telegram while I test it with curl below 
![Uploading B05944D7-CFED-4029-A022-681F115AC5F4.jpeg…]()

 
![2E030C14-4F80-417F-8F58-19CD0B195F31](https://github.com/tgbot-collection/ytdlbot/assets/9069317/8bf51d44-30fa-41b1-bdfb-baad80755299)

**Comment by kang000feng** [comment]
> Network issue. Maybe your ISP/country has blocked Telegram. Try to use proxy or switch to another open and free network.

![C1D438B7-8848-4C36-B6D6-C303E4F5C25C](https://github.com/tgbot-collection/ytdlbot/assets/9069317/0d42bd55-035a-497a-9d4a-538bb848df95)

**Comment by BennyThink** [comment]
try to run with host network

**Comment by kang000feng** [comment]
> # cat env/ytdl.env
> 
> PYRO_WORKERS=100
> TOKEN=170IluBY
> APP_ID=123
> APP_HASH=123

Dear developer,

May I ask How to enable the download playlist support ?
Which other variables should be configured except PLAYLIST_SUPPORT=True  ? 
 
And are there any wrong with below setting?

IPv6=True
ENABLE_FFMPEG=True
ENABLE_ARIA2=True

since I setup ytdlbot for myself , what value should I input for the variable "FREE_DOWNLOAD= " ?

thanks for your kind reply.

**Comment by BennyThink** [comment]
PLAYLIST_SUPPORT=1
FREE_DOWNLOAD does not matter if you don't enable VIP mode

**Comment by kang000feng** [comment]
> PLAYLIST_SUPPORT=1
> FREE_DOWNLOAD does not matter if you don't enable VIP mode

Thanks for your patience. May I ask what is the address do you indicate in this error message of screenshot below  ? Can you please let me know the url ? Because I logged into docker container and test the telegram port is open there , so I am confused what address the ytdlbot was failing to connect exactly ? 

Tks again. 

![8257F519-4282-4087-B383-1AB3E1DF221C](https://github.com/tgbot-collection/ytdlbot/assets/9069317/8e8bb10c-6383-4029-8fd4-76ceb49a41b4)
![313E5DDE-67A6-4D13-9FE9-72E23D9103AC](https://github.com/tgbot-collection/ytdlbot/assets/9069317/f9459aed-1e35-42c4-bcea-169ec22f83c8)

**Comment by kang000feng** [comment]
Dear developer,

I just enable ipv6 support and find out the container error message is shifting from  "[Errno 99] address not available " to  "time out ",  here attached the log , May i ask what address exactly connection.py is trying to connect to ?   

Thanks

**Comment by kang000feng** [comment]
FYI 
![5CC37514-C4CE-4212-B242-03B90CBCB922](https://github.com/tgbot-collection/ytdlbot/assets/9069317/55982b5e-83bf-45ea-9313-cf64ff3cb5b2)

**Comment by BennyThink** [comment]
if you want to enable ytdl's IPv6 in container, you must use host network mode. https://docs.docker.com/network/network-tutorial-host/ 

From the screenshot there are something wrong with your network on your host OS, i.e. iptables chain NAT, FORWARD. You need to dig in further to figure out what's going on.

**Comment by kang000feng** [comment]
> if you want to enable ytdl's IPv6 in container, you must use host network mode. https://docs.docker.com/network/network-tutorial-host/ 
> 
> 
> 
> From the screenshot there are something wrong with your network on your host OS, i.e. iptables chain NAT, FORWARD. You need to dig in further to figure out what's going on.

Dear developer,

Thanks for your reply. I think you misunderstood my screenshot above,  I never used the host network mode in above screenshot, I have been using the bridge network mode that has isolated network against host OS, moreover my host OS was fresh installed with DD command and iptables is pretty clean. 

And just now I changed network mode to host , but the error is same as last.

Here's the error output with host network mode 
![image](https://github.com/tgbot-collection/ytdlbot/assets/9069317/08db158e-d1e1-4c2e-a73f-61bf8a1ccf85)
