### ISSUE TITLE
ignore new codec 

### ISSUE THREAD

**Issue by gengjiawen** [tgbot-collection/ytdlbot#260]
https://youtu.be/setoOW2iXao, youtube recently add a new codec `vp09.00.41.08`, need to exclude.

https://github.com/tgbot-collection/ytdlbot/blob/b85b559efa934babf2a456943fd93070dd03ef36/ytdlbot/downloader.py#L174

**Comment by BennyThink** [comment]
🤔️ Why?

**Comment by gengjiawen** [comment]
same as webm and av01 are not streamable on telegram (iOS device and web)
