### ISSUE TITLE
Integration Suggestion: Rclone Upload to Cloud Storage

### ISSUE THREAD

**Issue by Adonis142857** [tgbot-collection/ytdlbot#282]
Hello,

I recently came across your ytdlbot project and deployed my own bot for personal use. I must say the experience has been outstanding, and I'm genuinely grateful for the amazing tool you've developed.

I have a suggestion for a potential feature enhancement. Would it be possible to integrate Rclone, so that after sending a link to the bot, it can directly upload the file to cloud storage using Rclone? I believe this would be a valuable addition to the bot's capabilities.

Thank you for considering my suggestion. Keep up the great work!

**Comment by Abhi-xt** [comment]
@Adonis142857 Bro On Which Platform you deployed it ?

**Comment by Adonis142857** [comment]
I deployed it using Docker.

**Comment by BennyThink** [comment]
It's supported now. Setup `RCLONE` to the path you have with rclone. It should work.
