### ISSUE TITLE
Error The msg_id is too low, the client time has to be synchronized.

### ISSUE THREAD

**Issue by yeshua-aguilar** [tgbot-collection/ytdlbot#287]
Hello good morning, afternoon or evening, I have been wanting to try your bot on my pc, I have already configured the bot but when I run it I get the error

ERROR: The msg_id is too low, the client time has to be synchronized.

I am running the bot with python 3.11.5, and since you are the creator of the bot, I humbly come here to ask you what I can do to solve the error.

### **captura**

![image](https://github.com/tgbot-collection/ytdlbot/assets/81573986/c4bdee67-079e-4369-a284-6970aa5a0ded)

**Comment by BennyThink** [comment]
which version of pyrogram are you using? Did you tried `pip install -r requirements.txt`?

**Comment by BennyThink** [comment]
Also, please try to sync your system date and time

**Comment by yeshua-aguilar** [comment]
Hello, after analyzing your code, I have given the solution to the problem that is when you run your bot this creates a file that ends in ytdl-main.session and what happens when you stop the bot this file stays there and when you run it again gives this error. what to do is just delete this file that ends in ytdl-main.session and start the bot and it works correctly again creating again the file ytdl-main.session.

![image](https://github.com/tgbot-collection/ytdlbot/assets/81573986/13a03162-a2a1-46c7-9e05-ff7b253f9422)

I was able to test your bot and it is great, I already put a star to your repository. thank you very much.

**Comment by BennyThink** [comment]
Good to know. Consider it as fixed

**Comment by vuisme** [comment]
> Xin chào, sau khi phân tích code của bạn, mình đã đưa ra giải pháp cho vấn đề đó là khi các bạn chạy bot này sẽ tạo ra một file kết thúc bằng ytdl-main.session và điều gì sẽ xảy ra khi các bạn dừng bot file này vẫn ở đó và khi các bạn chạy lại lại cho lỗi này. Việc cần làm chỉ là xóa tệp này kết thúc bằng ytdl-main.session và khởi động bot và nó hoạt động chính xác trở lại tạo lại tệp ytdl-main.session.
> 
> ![ảnh](https://user-images.githubusercontent.com/81573986/264192574-13a03162-a2a1-46c7-9e05-ff7b253f9422.png)
> 
> Tôi đã có thể kiểm tra bot của bạn và thật tuyệt, tôi đã đặt một ngôi sao vào kho lưu trữ của bạn. Cảm ơn rất nhiều.

Can you give me your solution?

**Comment by BennyThink** [comment]
Just delete the session file and start the bot again.

**Comment by vuisme** [comment]
> Just delete the session file and start the bot again.
I use k8s. I get this error often recently. After restart pod it's work again but that bug comback after 1-2 hour running

**Comment by vuisme** [comment]
[p6saaf84pue431cwcudnaqlu2_logs.txt](https://github.com/tgbot-collection/ytdlbot/files/12876174/p6saaf84pue431cwcudnaqlu2_logs.txt)

**Comment by vuisme** [comment]
New problemt on Celery mode.
The error only appears after receiving a query from the Master. Therefore, there will be a case where the first message after a period of time when Idle bot does not respond, just a message saying please wait (In fact, the Worker side reports an error and crashes, deletes the session...). Only works when resubmitting another query.

**Comment by BennyThink** [comment]
I upgraded to pyrogram v2. This issue should be fixed. If not feel free to reopen it
