### ISSUE TITLE
Pyrogram version compatibility issue.

### ISSUE THREAD

**Issue by rule-airport** [tgbot-collection/ytdlbot#288]
Why isn't it compatible with Pyrogram 2.0.106?
You have kept everything else up to date, but Pyrogram has not been adapted.

**Comment by BennyThink** [comment]
because it's not compatible with celery. At least by the time I was testing it's not working properly. I would be very happy to see a PR for it.

**Comment by rule-airport** [comment]
In the latest version, there seems to be no problem. You can try it out. I forked a copy and am also trying to adapt it, but I haven't learned Python before. I struggled with ChatGPT and the official documentation for most of the time. It can download files under 2GB, but I have been unable to pass user.is_premium to save_file(), which keeps causing errors. If possible, I will upload my adapted code to the repository so that you can quickly understand it (note: I modified some of the original code to meet my needs). Thank you very much.

**Comment by BennyThink** [comment]
Okay I see. Even bots created by premium users are not supported files bigger than 2GB. I will try to use the latest version

**Comment by rule-airport** [comment]
My current version now supports files larger than 2GB, but setting it up is a bit troublesome and there are many bugs, such as the inability to restrict people and sending messages not within the bot but to other locations. You can refer to it if you want, thank you.

**Comment by BennyThink** [comment]
<img width="1381" alt="image" src="https://github.com/tgbot-collection/ytdlbot/assets/14024832/31d31f05-2e31-429d-9eb6-01019bed6272">

It's not compatible with celery

* celery==5.3.1
* pyrogram==2.0.106

**Comment by BennyThink** [comment]
Should be fixed... give me some time to test..

**Comment by BennyThink** [comment]
online now
