### ISSUE TITLE
To download Instagram videos, you can use yt-dlp to download

### ISSUE THREAD

**Issue by rule-airport** [tgbot-collection/ytdlbot#319]
When using yt-dlp to download, just add cookies.

refer to:
https://github.com/rule-airport/ytdlbot/commit/a63d72e558756f2ef18a2542b2bd0c74657ff630

**Comment by BennyThink** [comment]
yes it is but it requires to add cookie to every worker, also doing this might get your account banned.

**Comment by rule-airport** [comment]
> yes it is but it requires to add cookie to every worker, also doing this might get your account banned.

I saw that your instagram.py also uses INSTAGRAM_SESSION. I can only say that it is safer to build it yourself. You may be able to ask users who need to download Instagram videos to enter their own INSTAGRAM_SESSION in telegram. Otherwise, just using one of your INSTAGRAM_SESSION will not work. It might be possible to get your account banned.

**Comment by BennyThink** [comment]
No it's not safer. Meta is constantly monitoring those scraping actions.

That file will be deleted soon because it's not used anywhere 🤣

![photo1702407273](https://github.com/tgbot-collection/ytdlbot/assets/14024832/0bb5ffc4-718b-48a8-96a1-abfbfa67e822)

**Comment by rule-airport** [comment]
> No it's not safer. Meta is constantly monitoring those scraping actions.
> 
> That file will be deleted soon because it's not used anywhere 🤣
> 
> ![photo1702407273](https://private-user-images.githubusercontent.com/14024832/290180697-0bb5ffc4-718b-48a8-96a1-abfbfa67e822.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0Njg5NjUsIm5iZiI6MTcwMjQ2ODY2NSwicGF0aCI6Ii8xNDAyNDgzMi8yOTAxODA2OTctMGJiNWZmYzQtNzE4Yi00OGE4LTk2YTEtYWJmYmZhNjdlODIyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxMTU3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjE3ZWE2ZDIzOTRlZmRkNjY5NTJlOTUzMDQ0OWEzYzYwOGJhZDE1OWU0YTZlYTM4NGNjMTAwMjMzOTE4ZTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8DA4l5NCs-3NGMKkQ7XHyD1SffCpka4cu29XNI8Ii1g)

If captured in incognito mode, the employee's cookie can be saved for a longer period of time. My Twitter cookie has been saved for almost half a year and has not been updated. As for Instagram, I rarely use it. I captured it when I updated the code last time. After taking it, three days have passed and it is in normal use.This is what I can think of, hope it helps.

**Comment by BennyThink** [comment]
No matter how meta can still identity you using the session id. They first paused my access, then verified my phone number. And last this is what I have, a strict warning. :-(
