### ISSUE TITLE
Unknow bug - Video wasn't upload

### ISSUE THREAD

**Issue by vuisme** [tgbot-collection/ytdlbot#323]
Sometime my bot can not upload video to Archive Group. I try to track and debug but nothing error show on exception. It's just gone and stuck at this screen and logs
![image](https://github.com/tgbot-collection/ytdlbot/assets/96235876/b06fe509-500c-4b56-bc41-bae0d6cbcb27)
![image](https://github.com/tgbot-collection/ytdlbot/assets/96235876/49bc9f6f-d9e0-43fe-bea2-a63a9509860b)

I'm using celery mode. How to debug status after send video?
![image](https://github.com/tgbot-collection/ytdlbot/assets/96235876/e3cc1a20-d6bb-4e38-88ab-04cfa049fc7a)

**Comment by BennyThink** [comment]
Is your bot busy with uploading? By default pyrogram will only upload one file at a time. You may need to adjust `max_concurrent_transmissions`, see here

https://github.com/tgbot-collection/ytdlbot/commit/9f9ff0a79492e43616c41208a55fe86bee6f00d2

**Comment by vuisme** [comment]
I have tried shutting down all Masters and Workers. Only tested with 1 single download link. This is full log
[ytdl-worker.log](https://github.com/tgbot-collection/ytdlbot/files/13750963/ytdl-worker.log)

**Comment by BennyThink** [comment]
From the log there's nothing strange. Can you try to adjust `PYRO_WORKERS` and `max_concurrent_transmissions` to appropriate value? Also try to pull the latest code, measure network activity by `vnstat -l` or similar tools

**Comment by vuisme** [comment]
> From the log there's nothing strange. Can you try to adjust `PYRO_WORKERS` and `max_concurrent_transmissions` to appropriate value? Also try to pull the latest code, measure network activity by `vnstat -l` or similar tools
Because 
Hi Benny. I try remove 3 line:
```
                progress=upload_hook,
                progress_args=(bot_msg,),
                reply_markup=markup,
```
on send video and it's can upload again. Maybe have a bug when select reply message or something. I will follow and update soon

**Comment by BennyThink** [comment]
Good to know. It may also because of [upload_hook ](https://github.com/pyrogram/pyrogram/issues/663)

**Comment by vuisme** [comment]
I'm not sure if this is the cause. But it seems that if there is any error during the upload process, the redis.update_metrics("video_success") function will not be called, leading to the following tasks being affected including restarting the workers.
I tried putting redis.update_metrics("video_success") above the send commands and tracking more.

![image](https://github.com/tgbot-collection/ytdlbot/assets/96235876/f7b743c8-caa8-4699-aee9-3a97f8ecec60)

**Comment by BennyThink** [comment]
Can you try to manually trigger an error when uploading files(like switch on/off your wifi)? I am not sure if `update_metrics` is the case but it could be an deadlock somewhere..

**Comment by vuisme** [comment]
> Can you try to manually trigger an error when uploading files(like switch on/off your wifi)? I am not sure if `update_metrics` is the case but it could be an deadlock somewhere..

I still get the error. really annoying. Common when restarting a worker to update a new image or using the /patch command. After that, all image and video upload tasks will not be able to be sent. Just gone. It can only be temporarily fixed by deleting 4 lines
```
                 progress=upload_hook,
                 progress_args=(bot_msg,),
                 reply_markup=markup,
                 **meta,
```
and reboot. And if I encounter the problem again later, I have to re-add these 4 lines and restart again LOL. it seems that changing the submitted function's arguments solves the task hanging problem

**Comment by BennyThink** [comment]
then most likely it's caused by ``` progress=upload_hook,
                 progress_args=(bot_msg,),``` 🫠

**Comment by SilverBull** [comment]
I don't wanna hijack this, but the bot should function in group then? I should open a different issue to understand why I can't make it work in a private group?

**Comment by vuisme** [comment]
> I don't wanna hijack this, but the bot should function in group then? I should open a different issue to understand why I can't make it work in a private group?

It's should be work with command: /ytdl <link> in a group
