### ISSUE TITLE
Huge Respect for the code ! But One Small Doubt 

### ISSUE THREAD

**Issue by Abel360w** [tgbot-collection/ytdlbot#333]
**Hey I liked Your Code Very Much But it is not working for me because i use a free platform like render and created a web service because the code dont have any you know  keep alive.py that opens and says i am alive nevermind can you tell me where did you host the bot and can you pls tell me how to change the payment info to my deatails in /buy also if you can pls recommend me a free hosting were i can host it for free 24/7**_Pls Reply_

                                                                                                                         **Thanks For Making This Amazing Bot
                                                                                                                                                           By Abel**

**Comment by BennyThink** [comment]
* change payment info in `ytdlbot/constant.py` and `ytdlbot/config.py`
* I host the bot in vultr
* no recommendation for free hosting service:-(

**Comment by craftap** [comment]
Hey i have another issue the instagram downpoad is not working pls fix
