### ISSUE TITLE
There Is An Error 

### ISSUE THREAD

**Issue by Phythogram** [tgbot-collection/ytdlbot#338]
- The /ping command also not working it says kombu.exceptions.OperationalError: Error -2 connecting to redis:6379. Name or service not known In the Console . Its Not Showing Like This- 
                                 YouTube-dl has been running for 13 days, 9:41:53 from 2024-01-10 15:24:12 +0000😄

-The Required membership I cannot Understand How to set it or its not working

-How To Set Required Membership Thing This My my Channel Link https://t.me/Anonxc Pls Show How To Set It !

Code:

 membership requires: the format could be username(without @ sign)/chat_id of channel or group.
 You need to add the bot to this group/channel as admin
REQUIRED_MEMBERSHIP: str = os.getenv("REQUIRED_MEMBERSHIP", "")

**Comment by BennyThink** [comment]
* ping only works for celery mode
* `REQUIRED_MEMBERSHIP=your_group_username`
