### ISSUE TITLE
Thanks For The Great Help ! But One More Clearence and Question ?

### ISSUE THREAD

**Issue by Abel360w** [tgbot-collection/ytdlbot#341]
### Finally I was Able to Set The Required Membership Thing And Everything Thank you so much you guys are the best developers/coders i have ever seen who respond to all the questions thanks for the help .

**But I Need One Last Help These Are My Questions:

1 - How To Enable Celery  And Properly RUN The /Ping Command !

2 - What's A Redis Server Can i Setup It for Free Or How To setup It !

3 - How To Set Up The Payment Info To My Credit Card And Change The TRX Qr Code To mine What Changes Are Required In The Ytdl_bot.py And Constant.py !

4 - How To Setup /redeem Command !

I Hope You Guys Help Me ! You Guys Are Right I Am Not A coder And Dont Know How To Change Things That's Why I am Asking !**

**Comment by BennyThink** [comment]
You should read the doc https://github.com/tgbot-collection/ytdlbot#complete-deployment-guide-for-docker-compose
