### ISSUE TITLE
One  Small Doubt ! and Update Request

### ISSUE THREAD

**Issue by Abel360w** [tgbot-collection/ytdlbot#347]
Bro When I Try To Test The Inline MODE Nothing Is Showing like this 
<p align="center"><img src="https://github.com/tgbot-collection/ytdlbot/assets/152060504/c4fd4ac7-d401-495d-be4e-3970615164ed?raw=true" width="200"/></p>
and can you conevert all the / commands to buttons so there is no mess like this
<p align="center"><img src="https://github.com/tgbot-collection/ytdlbot/assets/152060504/00782f0b-85ff-43e4-a951-123f6cdb7d31?raw=true" width="200"/></p>
and show history is not showing/working is it because i didnt setup the mysql and redis database

**Comment by craftap** [comment]
same Problem Here Pls Tell Them To Change To Mongodb And Atleast add a tutorial video on how to host and make it properly run on render koyed heruko etc

**Comment by BennyThink** [comment]
you need to enable history in `/settings`. it's off by default.
