### ISSUE TITLE
Hey Brother One Request !

### ISSUE THREAD

**Issue by Abel360w** [tgbot-collection/ytdlbot#350]
**CAN YOU PLS UPDATE THE CODE SO THAT  IT SHOULD BE ABLE TO SHOW ALL THE FILES THAT ALL THE BOT USERS(ALL USERS) HAVE DOWNLOADED IN THE INLINE MODE !** 

### One Extra Request Pls Read

**Can You Tell The Reason Also Why You Are Not Changing To MongoDb It SHOULD have been way easy with that i hope you understood my request and one last request if you dont want mongodb in your code can you code it for me my personal bot you can type the code as a response or comment no problem pls if you are doing it pls completly remove the redis and mysql you are a great developer all the best !😉**

**Comment by BennyThink** [comment]
I don't have time to migrate to MongoDB.
> ALL THE BOT USERS(ALL USERS) HAVE DOWNLOADED
No. This violates user's privacy.
