### ISSUE TITLE
Feature Update Request

### ISSUE THREAD

**Issue by craftap** [tgbot-collection/ytdlbot#355]
Hello Mr.Benny I Have Recently Viewed Your Inline Update And other peoples issues I Have To Tell Something.

1. Add A Button Called Files Visibility Private/Public If Its Public Whenever A user Searches Something And If  It Is Saved By Other User and the bot it should show all the public users downloaded files according to the other users query and if it is private the file of the user should not be shown in inline mode to other users//.

And Whenever The User Types @botname In The Chat It Should Say Like Welcome To Inline Mode and Other Texts Not Files Files Should Be Only Shown According Their Query.

3. Add A Command Called All Files Which Shows The All The Downloaded Files Of The Users If Thier Show Files showing is set to true its not /show_history command this all_files command should show the downloaded files of all the users who's preference is public and Multiple Files Should Be seprated With A Button Called Next Page .

4. Add Another Command Called statistics So That It Shows From Which Website is the most number of files downloaded for example like this.,
                           Facebook: 200 Files Downloaded 
                           Youtube: 1003 Files Downloaded
                           Instagram: 30 Files Downloaded 
One More Called Errors/Failed: 10 Files Its Should Refresh Every 10 OR 15 MINUTES

I Hope You Like This Request From A Noob Developer !

**Comment by SanujaNS** [comment]
Hello @craftap ,

4th one 'statistics'. it's a good feature but isn't it a bit much when history involves public data?

**Comment by craftap** [comment]
no no i Think it can be done in some days or weeks but not impossible

**Comment by SanujaNS** [comment]
> @SanujaNSno no i Think it can be done in some days or weeks but not impossible

What I meant was that involving public data seems unnecessary. It's a large amount of data that most users don't utilize. Most of the users use this @BennyThink public bot is just to get their desired videos by providing URLs, and and self-hosted users typically use this by their own or by their own groups.

Ultimately, the decision rests with @BennyThink

**Comment by craftap** [comment]
Ok Pls Tell Him I hope a positive response

**Comment by BennyThink** [comment]
those feature won't be implemented, please implement yourself within a fork.
