### ISSUE TITLE
telegram video url  can't reback a right video

### ISSUE THREAD

**Issue by yaovenus** [tgbot-collection/ytdlbot#357]
when i send a telegram video url to the selfdeploy bot , it reback a worry video.

**Comment by SanujaNS** [comment]
> when i send a telegram video url to the selfdeploy bot , it reback a worry video.

Hello @yaovenus,

I'm struggling to understand your issue based on just this one sentence you typed. Could you provide more details about what you're experiencing? Also include URLs("telegram video url") you are talking about and screenshot of the process.

**Comment by yaovenus** [comment]
![IMG_20240223_173704](https://github.com/tgbot-collection/ytdlbot/assets/22662509/580e7d69-ad39-467d-9054-acca44cf1e21)
![IMG_20240223_173712](https://github.com/tgbot-collection/ytdlbot/assets/22662509/ec77d01a-0ceb-4684-818d-f76759bf17df)

**Comment by SanujaNS** [comment]
@BennyThink @yaovenus 

Terminal Output: [https://pastebin.mozilla.org/5d0Ykz4a/raw](https://pastebin.mozilla.org/5d0Ykz4a/raw)

**Bug:** Bot keeps uploading previous video printing
`Setting metrics: cache_hit`

![image](https://github.com/tgbot-collection/ytdlbot/assets/66342986/ddcb398f-b826-48d4-bd19-82fb852f15ae)
![image](https://github.com/tgbot-collection/ytdlbot/assets/66342986/63e0a4f5-ee7b-4df0-a3b7-597cbf780868)

**Comment by BennyThink** [comment]
fixed in 5be9d65f38b395a72352cb57f04cd5f6990a7a45
