### ISSUE TITLE
Downloading a part of any YouTube video

### ISSUE THREAD

**Issue by iit-aditya** [tgbot-collection/ytdlbot#36]
I need videos from youtube in striped format.
Like I need only a part of this video
https://youtu.be/kEUlG3_Ouxs
Like it's a 6 hours class and I need only till starting 1:15:00 hours
If possible, plz do help😊
And add this feature.

**Comment by BennyThink** [comment]
This appears to be problematic for current implementation. I don't see if yt-dlp supports that.

Labeled it with won't fix until yt-dlp supports that.

**Comment by EDM115** [comment]
Actually, some ways exists to download only a part of the video :  
[▫️With ffmepg](https://www.reddit.com/r/youtubedl/comments/kvzoy3/comment/gj1zbe8/)  
[▫️Here's how it works with youtube-dl, might also works with yt-dlp](https://www.reddit.com/r/youtubedl/wiki/downloadingytsegments/)  
[▫️With a `.bat` script](https://www.reddit.com/r/youtubedl/comments/ru7bnv/can_someone_help_with_me_completing_with_this_bat/)  

Else, yt-dlp offers also to split a video if it have specified chapters :  
*Split video by chapters: Videos can be split into multiple files based on chapters using `--split-chapters`*
