### ISSUE TITLE
How To Setup

### ISSUE THREAD

**Issue by Bot24280** [tgbot-collection/ytdlbot#365]
**Plz help mee...** _how i setup_ **i can'tunderstand**

**Comment by SanujaNS** [comment]
[https://github.com/tgbot-collection/ytdlbot#how-to-deploy](https://github.com/tgbot-collection/ytdlbot#how-to-deploy)

The deployment guide is designed to be very beginner-friendly, with step-by-step instructions. Give us specifics on what you don't understand. If you can't point out the exact part confusing you, then you clearly haven't read it closely enough.

**Comment by Bot24280** [comment]
![Screenshot_20240329-013805_Chrome](https://github.com/tgbot-collection/ytdlbot/assets/164179316/67a62e84-bd44-47d6-87ed-60d0d63e0303)
**How to solve**
