### ISSUE TITLE
Database.. 

### ISSUE THREAD

**Issue by Ashrafmdmatin41** [tgbot-collection/ytdlbot#373]
Boss Please Change Database From My Sql To Mongodb Because I Am Android User So Please please change database to Mongodb and in readme update again and explain about redis variable is this important because bcz now redis is paid + once check heroku docker bcz i am gonna to deploy to heroku after this 

And Thanku for this

**Comment by BennyThink** [comment]
I won't add support for mongodb because I don't have any time for this.
