### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by addy005** [tgbot-collection/ytdlbot#392]
Hello, I'm getting an error when downloading some videos from sites other than YouTube, while your bot is working fine. Maybe the code is outdated; I hope you'll update it so I can host my own bot. I appreciate your work, brother. Is there any way to make it faster? I have a Xeon server with 8 cores and 10 Gbps speed, and it's not even using 5%.

**Comment by SanujaNS** [comment]
Hello @addy005 ,

Could you provide us with more details, such as the specific error message or a screenshot of the problem? Without a clear understanding of the issue, it's difficult to provide an effective solution.

**Comment by addy005** [comment]
sent on telegram brother
