### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by kytv007** [tgbot-collection/ytdlbot#396]
fatal: not a git repository (or any of the parent directories): .git

**Comment by SanujaNS** [comment]
I can't give a definitive answer for the first two. However, for this issue doesn't seem to be a problem; it's likely occurring because you removed the .git directory after cloning the project.

**Don't try to change or delete the files if you don't know what you are doing.**

**Comment by kytv007** [comment]
I didn't delete/change anything.

**Comment by SanujaNS** [comment]
Begin by cloning the project and closely follow the step-by-step instructions provided in [the guide](https://github.com/tgbot-collection/ytdlbot#run-natively-on-your-machine). We've put considerable effort into making the guide very beginner friendly, so as long as you adhere to the steps outlined, you should not encounter any issues.

**Comment by BennyThink** [comment]
You need to clone this project. Simply code - download zip will be missing .git
