### ISSUE TITLE
Support for /about and /help commands

### ISSUE THREAD

**Issue by Korb** [tgbot-collection/ytdlbot#403]
![Screenshot_20240704_114934_org telegram messenger beta](https://github.com/tgbot-collection/ytdlbot/assets/3509797/1c29b9fd-1987-4ac2-9ad8-d1e1e91ff329)

**Comment by SanujaNS** [comment]
It seems that there's a problem with your bot deployment, as the bot doesn't seem to have started correctly. Before creating a new issue, take a moment to review the deployment process carefully and make sure that all steps have been followed accurately.
