### ISSUE TITLE
Error Download 

### ISSUE THREAD

**Issue by SalmaniRamin** [tgbot-collection/ytdlbot#409]
Hello, when playing music with YouTube, this error is seen, what should we do? 

Sign in to confirm you’re not a bot. This helps protect our community. Learn more

Thank you.

**Comment by SanujaNS** [comment]
Hello @SalmaniRamin ,

I have checked both official bots:

 EU🇪🇺:  [@benny_2ytdlbot](https://t.me/benny_2ytdlbot)
 SG🇸🇬:  [@benny_ytdlbot](https://t.me/benny_ytdlbot)
 
They seem to be functioning correctly. By any chance, are you hosting your own bot? If that's the case, the problem might be related to YouTube blocking your IP. Could you please provide the URLs that are causing errors? This information will help us troubleshoot the issue further.

**Comment by BennyThink** [comment]
Your IP has blocked by YouTube. Try to switch an IP or use another provider.
