### ISSUE TITLE
how can i download 4k youtube video via official bot？

### ISSUE THREAD

**Issue by KiritoGuugk** [tgbot-collection/ytdlbot#412]
how can i download 4k youtube video via official bot？

**Comment by BennyThink** [comment]
settings - send as file

**Comment by BennyThink** [comment]
that probably means yt-dlp is unable to download 4k version of this video due to streaming thingy.

**Comment by BennyThink** [comment]
Just updated, can you try again to see if it works for you now?

**Comment by KiritoGuugk** [comment]
> Just updated, can you try again to see if it works for you now?

yes it works
