### ISSUE TITLE
Youtube-links get corruption when they contain some special characters

### ISSUE THREAD

**Issue by PROger4ever** [tgbot-collection/ytdlbot#456]
### Problem
When an youtube-link contains double hyphen/dash/minus `--`, **ytdlbot** sends the video with link without `--`:
`https://youtu.be/SE1EwODM--s` ==> `https://youtu.be/SE1EwODMs`
I think there are a lot of other characters besides `--` that can break messages and links.
At least this makes audio conversion crash.

### Some research
The link becomes changed somewhere in `pyrogram.Client.send_video()` locally while preprocessing the message. When I send a telegram-message with `--` manually through **curl**, the message got send as is.

### Proposals
1. Send all messages (not only videos) with **parse_mode** disabled:
```python
res_msg = client.send_*(
  # ...
  caption=cap
  # ...
  parse_mode: enums.ParseMode.DISABLED, # !!!
)
```
2. Send all messages (not only videos) with `HTML` **parse_mode** and escape special chars:
```python
# ...
cap = html.escape(cap)
# ...
res_msg = client.send_*(
  # ...
  caption=cap
  # ...
  parse_mode: enums.ParseMode.HTML, # !!!
)
```

### Reference
- [Pyrogram / Text Formatting](https://docs.pyrogram.org/topics/text-formatting)
- [pyrogram.enums.ParseMode](https://docs.pyrogram.org/api/enums/ParseMode)
- [Telegram Bot API / formatting options](https://core.telegram.org/bots/api#formatting-options)

**Comment by SanujaNS** [comment]
Hello @PROger4ever ,

I have addressed the issue you reported with ([Improve caption (Fix #456)](https://github.com/tgbot-collection/ytdlbot/pull/457)). Please take a moment to verify that the problem has been resolved to your satisfaction and close the current issue.

Should you encounter any further difficulties or have additional concerns, do not hesitate to open a new issue.

Thank you.
