### ISSUE TITLE
VP9 Codec Avoidance Not Working

### ISSUE THREAD

**Issue by aiovin** [tgbot-collection/ytdlbot#472]
I'm using the python version of the bot and the line in [downloader.py](https://github.com/tgbot-collection/ytdlbot/blob/3adb096b99df9c2b387eaa2043571ac84545fc9d/ytdlbot/downloader.py#L212) doesn't seem to work, at least with Instagram videos. I tried changing the first rule to something different, but it caused errors or resulted in weirdly downloaded files. So, I gave up and just deleted the first rule. The second rule is working fine for now, but I still wanted to let you know.

**Comment by SanujaNS** [comment]
Hello @aiovin ,

Thank you for reporting the issue.

> To help us better understand the problem, could you please clarify if you're using the `/spdl` command to download the Instagram video or did you send the URL without any commands?

If you're sending the URL without any commands, yt-dlp will download it according to the `formats` list variable. For instance, these are the available formats for an Instagram reel:
```
ID                      EXT RESOLUTION │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC     ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
dash-917837406733370ad  m4a audio only │ ≈144.25KiB   78k https │ audio only          mp4a.40.5  78k 44k DASH audio, m4a_dash
dash-1054233199722717vd mp4 360x640    │ ≈160.43KiB   87k https │ vp09.00.21.08   87k video only         DASH video, mp4_dash
dash-526371887099581v   mp4 540x960    │ ≈343.72KiB  186k https │ vp09.00.30.08  186k video only         DASH video, mp4_dash
3                       mp4 640x1136   │                  https │ unknown             unknown
dash-2029964290759991v  mp4 720x1280   │ ≈555.99KiB  302k https │ vp09.00.31.08  302k video only         DASH video, mp4_dash
dash-853856276707532v   mp4 720x1280   │ ≈885.16KiB  480k https │ vp09.00.31.08  480k video only         DASH video, mp4_dash
dash-3815744595330709v  mp4 720x1280   │ ≈  1.30MiB  719k https │ vp09.00.31.08  719k video only         DASH video, mp4_dash
dash-394674780335953v   mp4 720x1280   │ ≈  1.88MiB 1042k https │ vp09.00.31.08 1042k video only         DASH video, mp4_dash
dash-1790671065027885v  mp4 1080x1920  │ ≈  2.66MiB 1480k https │ vp09.00.40.08 1480k video only         DASH video, mp4_dash
```

As you can see, all showing videos use the vp09 codec, so yt-dlp falls back to `best video + best audio`. That's what first line do and yt-dlp will handles this by downloading and merging `dash-1790671065027885v` for video and `dash-917837406733370ad` for audio, providing you with the optimal combined result.

I hope this explanation helps clarify the process and addresses your concerns. If you have any further questions or if there's anything else I can assist you with, please don't hesitate to reach out.

Thank you.

**Comment by aiovin** [comment]
@SanujaNS Yes, I sent only the link without using the `/spdl` command. Your table clarified the situation; if I understood correctly, the first rule ultimately means that any available codec will be chosen, and according to this table, vp09 will still be downloaded. However, to be honest, I still don’t quite understand how, if the first rule is removed, the bot sends the AVC codec when only vp09 is available for Instagram. Does this mean the bot performs codec conversion? Thank you in advance for your reply.

**Comment by SanujaNS** [comment]
Let me clarify further for you.

`"bestvideo[ext=mp4][vcodec!*=av01][vcodec!*=vp09]+bestaudio[ext=m4a]/bestvideo+bestaudio"`
First Entry:

> This rule prioritizes MP4 videos without AV1 (av01) or VP9 (vp09) codecs and combines them with M4A audio. If the preferred conditions aren't met, it falls back to the best video and best audio combination available.

`"bestvideo[vcodec^=avc]+bestaudio[acodec^=mp4a]/best[vcodec^=avc]/best"`
Second Entry:

> This rule focuses on AVC-encoded (H.264) videos and MP4A-encoded (AAC) audio, falling back to any available best format if those conditions aren't met.

`None`
Third Entry:

> This rule uses the default format behavior of yt-dlp and it will automatically selects the best available formats without applying any custom restrictions.

___

Regarding your question, the bot doesn't transcode videos. I even double-checked the process and found that the bot sends Instagram videos with `vp09` and `aac` codecs:

```
Stream #0:0[0x1](und): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709), 1080x1920, 6734 kb/s, 60 fps, 60 tbr, 15360 tbn (default)

Stream #0:1[0x2](und): Audio: aac (HE-AAC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 83 kb/s (default)
```
___

You can check,

Available formats with: `yt-dlp -F {URL}`

Codecs of the downloaded video: `ffmpeg -i {FILE_PATH}`

___

If you still left with concerns, don't hesitate to reach out. I'm more than happy to help.

P.S.: In order to address your specific concerns and help you out in the best tailored way possible, remember to include the relevant URLs in your follow-up correspondence.

**Comment by aiovin** [comment]
@SanujaNS Thank you for your detailed explanation of the rules. I wanted to add one thing. Sorry, I should have mentioned it before, i focused on the vp09 format because i found out it's not supported on Telegram on iOS (latest verion of the telegram, iOS and iPadOS 16.7.2) and macOS . Videos with the vp09 codec on those devices play with a frozen first frame and only the sound works.

**Comment by SanujaNS** [comment]
> @SanujaNS Thank you for your detailed explanation of the rules. I wanted to add one thing. Sorry, I should have mentioned it before, i focused on the vp09 format because i found out it's not supported on Telegram on iOS (latest verion of the telegram, iOS and iPadOS 16.7.2) and macOS . Videos with the vp09 codec on those devices play with a frozen first frame and only the sound works.

Sorry, I don't have hardware to test the problem, but after doing some digging, it's looks like problem is complete on Apple's side. While one solution could be transcoding the videos to a compatible codec, it would need more resources, so it won't likely to add to the bot.

If you're primarily interested in downloading Instagram media, another solution is to use `/spdl` but for it to handle Instagram, you need to configure an API. You can find many limited free APIs at [rapidapi.com](https://rapidapi.com/). Remember AI can be a valuable ally when you need help for something like this.

Is there anything else you need assistance with?

**Comment by aiovin** [comment]
@SanujaNS No, that's all, thanks for such detailed answers.

**Comment by SanujaNS** [comment]
> @SanujaNS No, that's all, thanks for such detailed answers.

No problem at all, happy to help!
I'll close this issue for now, but feel free to start a new one if you have any more questions or need assistance.

Thank you for reaching out.
