### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Bartixxx32** [tgbot-collection/ytdlbot#49]
Feature request:

- [x] #50
- [ ] 2. Set limit for selfhosted bot to do only one url at once, for example i send to it links in order

```
youtube.com/1
youtube.com/2
youtube.com/3
```
And it will process one by one to send output files in good order, not sending smaller first when doing concurrent downloads.

- [x] #51
- [x] #56
- [x] #55
- [x] #54
- [x] #52
- [x] #53

**Comment by BennyThink** [comment]
Create new issue for item 2. Close this now.
