### ISSUE TITLE
Feature request : direct audio and metadata edit

### ISSUE THREAD

**Issue by EDM115** [tgbot-collection/ytdlbot#58]
It would be really cool if we can simply download only the audio by using a specific command (such as `/audio` or `/a`) with the link on the message, or by replying to a supported link with that command

Next enhancement that can be done is the ability to set custom metadata for the download we want (would work only for audio)
Like having a `/meta` command, then we specify the Artist and the Title
Example : `/meta Roy Knox:Until The End` (here the separator is a colon, but it could be something else)
I say this because when we have a mp3 file, Telegram shows the title and artist of the file
Can work as shown [here](https://github.com/yt-dlp/yt-dlp#modifying-metadata)

**Comment by EDM115** [comment]
Only problem for the `/meta` command : we need a delay, because we can't set metadata if the bot have instantly started the download 😭
Delay or confirmation through a Button

**Comment by BennyThink** [comment]
Audio only will be supported soon. I'll let you know when it's ready

As for the meta problem, I don't see the emergence and why you want this feature. If could be better if you can elaborate it more.

**Comment by BennyThink** [comment]
<img width="482" alt="image" src="https://user-images.githubusercontent.com/14024832/153110721-635bb28a-5f12-4833-8123-dd21ca373526.png">

Audio is supported now. You can set it globally.
