### ISSUE TITLE
Progressbar not accurate

### ISSUE THREAD

**Issue by EDM115** [tgbot-collection/ytdlbot#63]
We does actually have a little problem (not very important, but still)
The progress bar isn't accurate, as shown under :

![38% looks like 50%](https://i.imgur.com/M2ywSk9.png)
![82% looks like 95%](https://i.imgur.com/KffjCtE.png)

Why ?
Because of the definition of that progress bar (maybe you need to make changes [here](https://github.com/tgbot-collection/ytdlbot/blob/336616fba6d17e8f3dabaef7b5b99621fafa0c38/ytdlbot/downloader.py#L62))

The fact is that the completed string (█) takes way more space than the remaining string ( )

How to fix it ?
◽By changing those strings to something that takes the same place
    Examples : `⬢⬡` / `▰▱`
◽ By putting the progressbar in monospace (not sure it works)

**Comment by BennyThink** [comment]
will fix later this week

**Comment by BennyThink** [comment]
Just fixed. Can you see if it's accurate now?

**Comment by EDM115** [comment]
Yay, it's okay now ! ✅  
  
  
![30% ✅](https://i.imgur.com/QSQ0LVQ.png)  
  
![83% ✅](https://i.imgur.com/FytEjzh.png)
