### ISSUE TITLE
Settings Problem

### ISSUE THREAD

**Issue by kamileecher2** [tgbot-collection/ytdlbot#66]
The setting in the /settings section does not work

**Comment by kamileecher** [comment]
My bot

**Comment by BennyThink** [comment]
Setup and configure MySQL

**Comment by kamileecher** [comment]
![Screenshot_20220218-074824_Plus](https://user-images.githubusercontent.com/58888200/154619809-955b065d-f0cf-434d-96c3-036991f6aed9.jpg)


There is an error in your bot, it is not changed.  Unfortunately

**Comment by kamileecher** [comment]
bot freezes when pressing buttons

**Comment by BennyThink** [comment]
Confirmed it's an issue. Will fix it later this week

**Comment by kamileecher** [comment]
The second problem is that when I send the second link, the bot freezes again.

It would be better if you add the /status command

**Comment by BennyThink** [comment]
There's /ping that will show bot status

**Comment by kamileecher** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tgbot_ping/__init__.py", line 19, in get_runtime
    info, raw_data = __get_container_info(container_name, display_name)
  File "/usr/local/lib/python3.9/site-packages/tgbot_ping/__init__.py", line 62, in __get_container_info
    cpu = __calculate_cpu_percent(stats)
  File "/usr/local/lib/python3.9/site-packages/tgbot_ping/__init__.py", line 78, in __calculate_cpu_percent
    system_delta = float(d["cpu_stats"]["system_cpu_usage"]) - \
KeyError: 'system_cpu_usage'

**Comment by BennyThink** [comment]
Yes, that's #65.

**Comment by kamileecher** [comment]
Wouldn't it be better if you use mongodb instead of mysql,  is easier to use, creating my sql is a bit complicated oracle site membership is a bit tedious

**Comment by BennyThink** [comment]
fixed.
