### ISSUE TITLE
Heroku MYSQL

### ISSUE THREAD

**Issue by kamileecher** [tgbot-collection/ytdlbot#67]
how to add heroku to my sql is there any tutorial

**Comment by kamileecher** [comment]
Host 
Password
how do i set them up?  I never used mysql

**Comment by kamileecher** [comment]
![Screenshot_20220218-175804_Plus](https://user-images.githubusercontent.com/58888200/154706998-e7954ec0-b3ef-4b49-bc9a-60faa6ae088b.jpg)
I installed the special bot, but the settings are not visible in the settings section, so the other buttons are useless, how can I activate it.

**Comment by BennyThink** [comment]
I'll fix heroku in app.json later today.

**Comment by kamileecher2** [comment]
Thank you so much

**Comment by kamileecher** [comment]
Thank you, your settings for this mysql and /settings section will be great. 

settings are not available now

**Comment by BennyThink** [comment]
it appears heroku doesn't have MySQL server buildpack. I'll consider another workaround...

**Comment by kamileecher** [comment]
it would be great if you add heroku postgres
and settings section is not working

**Comment by BennyThink** [comment]
I'll consider using something like `fakemysql`

**Comment by kamileecher** [comment]
https://elephantsql.com


postgres://axzn7sjqisiao:BByn7LtFJs8qjz9anzjsntZ6Ln3xOimBYjVTWECqlTS0@chunee.db.elephantsql.com/axznsiao

Exp This good

**Comment by BennyThink** [comment]
Just pushed one commit. Can you fetch the latest code and see if it works?

Warning: settings won't persist if you restart dyno. But as long as you don't restart heroku app, it will persist.

**Comment by kamileecher** [comment]
do i need to add anything in app json

**Comment by BennyThink** [comment]
Nope you don't, just use the latest code.

**Comment by kamileecher** [comment]
Ok iyi am trying now wait

**Comment by kamileecher** [comment]
![Screenshot_20220220-180118_Plus](https://user-images.githubusercontent.com/58888200/154848951-9bc619c7-3ad4-4005-b187-1d40afb9ac42.jpg)


Settings not work

**Comment by kamileecher** [comment]
Now work bro thank you so much

**Comment by BennyThink** [comment]
No problem. Just remember restart the app will clear your settings data.

**Comment by kamileecher** [comment]
thank you even this way is enough

bro, broadcast feature is not working why

**Comment by BennyThink** [comment]
Broadcast? Do you mean broadcast.py? It's just one deprecated file and I forget to delete it

**Comment by kamileecher** [comment]
Thank you bro, such a feature would be great, can you activate it again?

**Comment by BennyThink** [comment]
Can you create another issues for this broadcast feature? I'm considering a more user friendly way of using it

**Comment by kamileecher** [comment]
Thank you so much
