### ISSUE TITLE
Bot Freezing

### ISSUE THREAD

**Issue by kamileecher** [tgbot-collection/ytdlbot#68]
![Screenshot_20220219-170558_Plus](https://user-images.githubusercontent.com/58888200/154804164-94767cc5-2d2d-44de-b662-fab1ffbd9fdd.jpg)

the bot sometimes freezes like this, the process is interrupted like this

**Comment by BennyThink** [comment]
If it freezes in download progress bar for a long time, ie 30 minutes, please send it again. There might be some error during download progress.

**Comment by kamileecher** [comment]
GID Task Stopped Add

Can you add task cancel command

/cancel taskno

**Comment by BennyThink** [comment]
cancel tasks is not possible due to technical issues.

**Comment by kamileecher** [comment]
Thank you sir
