### ISSUE TITLE
Please add an Split File Features

### ISSUE THREAD

**Issue by Tellybots** [tgbot-collection/ytdlbot#72]

**Comment by BennyThink** [comment]
larger video will be uploaded to transfer.sh for now. 

There was splitter functionality for a long time. However, until further feedbacks, I'll keep the same way.

If you want to enable it for your own deployment, you could remove comment [L203#](https://github.com/tgbot-collection/ytdlbot/blob/41a51cee9a7734400edcf91a48d7a66a1706c312/ytdlbot/downloader.py#L230)

**Comment by testerbot11** [comment]
Hello can you provide a bit elaborate instruction on how to enable the split feature for video files above 2GB? i am not sure which one from line 203 needs to be removed

**Comment by EDM115** [comment]
Remove `# ` at line 203

**Comment by testerbot11** [comment]
> Remove `# ` at line 203

Hello i tried removing as said and attached first pastebin from downloader.py filr file. I tried running the program but eneded up with an error which i pasted in pastebin link 2. Any help is appreciated. Thanks

pastebin 1: https://pastebin.com/wLdxgcpM
pastebin 2: https://pastebin.com/mTL1639c
