### ISSUE TITLE
Subscribe to youtube channel additional url format

### ISSUE THREAD

**Issue by edwardchenchen** [tgbot-collection/ytdlbot#78]
The following format is not supported:

https://www.youtube.com/c/szyzyg (https://www.youtube.com/channel/szyzyg is not accessible)

https://www.youtube.com/c/KerbalSpaceProgramOfficial

https://www.youtube.com/user/KerbalSPOfficial

**Comment by BennyThink** [comment]
<img width="490" alt="image" src="https://user-images.githubusercontent.com/14024832/156917452-7d967c35-da41-48bb-ae1d-3818a6e24a34.png">


fixed.
