### ISSUE TITLE
docker image builder fails at "build and push step"

### ISSUE THREAD

**Issue by EDM115** [tgbot-collection/ytdlbot#90]
```
/usr/bin/docker buildx build --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache-new,mode=max --iidfile /tmp/docker-build-push-GfE4m1/iidfile --platform linux/arm,linux/amd64,linux/arm64 --tag ***/ --tag ghcr.io/ --metadata-file /tmp/docker-build-push-GfE4m1/metadata-file --push .  
error: invalid tag "***/": invalid reference format  
Error: buildx failed with: error: invalid tag "***/": invalid reference format
```

**Comment by EDM115** [comment]
note that all secrets are filled

**Comment by BennyThink** [comment]
Are you building on your own machine or on a clone repository using GitHub Actions?
From the logs above I can see the secrets are not filled
* DOCKERHUB_USERNAME

**Comment by EDM115** [comment]
GitHub actions  
and secrets are filled  
  
![](https://telegra.ph/file/49af4ada7d9b2eab961bf.png)

**Comment by BennyThink** [comment]
Secrets are not passed to workflows.... did you read that hint?

**Comment by EDM115** [comment]
They do 🙂  
On my main [project](https://github.com/EDM115/github-stats-stonks) they actuall are used, and it works  
   
![](https://user-images.githubusercontent.com/82015596/162433537-f23d7e2a-f9db-4b05-b81b-7dace48cced0.png)
