### ISSUE TITLE
Environment variable AUTHORIZED_USER has no effect

### ISSUE THREAD

**Issue by gtjl12** [tgbot-collection/ytdlbot#92]
In “config.py” file, the code in line 43 to get the environment variable AUTHORIZED_USER  is

_#limitation settings
AUTHORIZED_USER: "str" = os.getenv("**AUTHORIZED**", "")_

However, the [guide](https://github.com/tgbot-collection/ytdlbot#31-set-environment-variables) says the environment variable to be  set is **AUTHORIZED_USER**, which will invalidate the user limitation function.
I thought it may be better to have the same description on both sides.

**Comment by BennyThink** [comment]
Thanks for the tip. I'll update the doc soon.
